### PR TITLE
Handling possible NPE and other stuff

### PR DESCRIPTION
**Pull request by xTheDoctah**
NPE Handling the getWorld Method can return null objects if it doesnt find any world. 
Instead of injecting into the constructor of SettingsRightTime the instance of CurrentTime you can use JavaPlugin.getPlugin(Class clazz) method.
Added more stuff to the .gitignore
Fixed Api-version in plugin.yml (The api-version MUST reflect the spigot api used for the plugin)

### CODE REVIEW

**Comment by OhmLibre** [comment]
Thank you!

I just took over Minecraft and I would keep those tips in mind.

**Comment by xTheDoctah** [comment]
No problem! If you wanna keep the 1.13 /1.14/1.15 compatibility. May I suggest you to use the 1.13.2 Api and set the api-version (in the plugin.yml) to 1.13

**Comment by xTheDoctah** [comment]
> 
> 
> Hello again!
> Can you remove the .gitignore file? It seems more complete but it doesn't cover more things than the one I have now.

Hey , I cleaned up the .gitIgnore, let me know if it's ok or if you wanna me to use this one (https://github.com/OhmLibre/CurrentTime/blob/master/.gitignore)

**Comment by OhmLibre** [comment]
Yes the original .gitignore file please :smile:

**Comment by xTheDoctah** [comment]
Done

**Pull request merged**
